# Directories
source: 'app'
destination: 'tmp/site'
plugins: 'plugins'

# Don't copy these files into the destination.
exclude: ['javascripts', 'stylesheets']

# Allow plugins that would be disabled on GitHub
safe: false

assets:
  # Decrease build time by caching between compilations.
  cache: '../tmp/assets'

  # Source assets from these directories.
  sources: ['javascripts', 'stylesheets']
