# Directories
destination: 'tmp/deploy'

# Enable Google Analytics.
google_analytics: true

assets:
  # Strip whitespace from CSS.
  css_compressor: 'sass'

  # Minify and strip whtiespace from JavaScript.
  js_compressor: 'uglifier'
