# Directories
source: 'app'
destination: 'tmp/site'
plugins: 'plugins'

# Don't copy these files into the destination.
exclude: ['images', 'javascripts', 'stylesheets']

# Disable Google Analytics in development.
google_analytics: false

# Allow plugins that would be disabled on GitHub
safe: false

assets:
  # Decrease build time by caching between compilations.
  cache: '../tmp/assets'

  # Disable gzipping in the asset pipeline.
  # s3_website takes care of this.
  gzip: false

  # Source assets from these directories.
  sources: ['images', 'javascripts', 'stylesheets']
