# Caching headers.
max_age:
  'assets/*': 31557600 # 1 year
  '*': 1800            # 30 minutes

# Smaller file sizes with gzip compression.
gzip: ['.html', '.css', '.js', '.json']

# Save money.
s3_reduced_redundancy: true
